from fastapi import APIRouter
from app.models.media_models import MediaConfigResponse, MediaConfigData, MediaProviderResponse, MediaCategoryResponse

router = APIRouter()

# Dummy Data matching the frontend implementation plan
# In the future, this data will be fetched from a database table
DUMMY_MEDIA_CONFIG = MediaConfigData(
    title="MEDIA",
    description="Choose a provider and category to start watching",
    pin="1234",
    providers=[
        MediaProviderResponse(
            id="premium_iptv_1",
            name="Premium IPTV",
            logo_url="https://example.com/images/premium_logo.png",
            is_active=True,
            categories=[
                MediaCategoryResponse(
                    id="WorldWide",
                    title="World TV",
                    type="live",
                    logo_url="https://raw.githubusercontent.com/freelancermilonid132bd-ui/apphub/refs/heads/main/world.svg",
                    color_hex="#2196F3",
                    playlist_url="https://iptv-org.github.io/iptv/index.m3u",
                ),
                MediaCategoryResponse(
                    id="movies",
                    title="Movies",
                    type="vod",
                    logo_url="https://raw.githubusercontent.com/freelancermilonid132bd-ui/apphub/refs/heads/main/favicon%20(9).ico",
                    color_hex="#9C27B0",
                    playlist_url="https://raw.githubusercontent.com/freelancermilonid132bd-ui/apphub/refs/heads/main/movie.m3u",
                ),
                MediaCategoryResponse(
                    id="sports",
                    title="Sports",
                    type="live",
                    logo_url="https://raw.githubusercontent.com/freelancermilonid132bd-ui/apphub/refs/heads/main/trophy.png",
                    color_hex="#4CAF50",
                    playlist_url="https://raw.githubusercontent.com/freelancermilonid132bd-ui/apphub/refs/heads/main/Sports2.m3u",
                ),
                MediaCategoryResponse(
                    id="BD",
                    title="Bangladesh",
                    type="live",
                    logo_url="https://raw.githubusercontent.com/freelancermilonid132bd-ui/apphub/refs/heads/main/Flag_of_Bangladesh.svg.png",
                    color_hex="#4CAF50",
                    playlist_url="https://raw.githubusercontent.com/imShakil/tvlink/refs/heads/main/iptv.m3u8",
                ),
                MediaCategoryResponse(
                    id="usa",
                    title="USA",
                    type="live",
                    logo_url="https://raw.githubusercontent.com/freelancermilonid132bd-ui/apphub/refs/heads/main/united-states-flag-icon.svg",
                    color_hex="#9C27B0",
                    playlist_url="https://raw.githubusercontent.com/freelancermilonid132bd-ui/apphub/refs/heads/main/usa.m3u",
                ),
                MediaCategoryResponse(
                    id="india",
                    title="India",
                    type="live",
                    logo_url="https://raw.githubusercontent.com/freelancermilonid132bd-ui/apphub/refs/heads/main/Flag_of_India.svg",
                    color_hex="#9C27B0",
                    playlist_url="https://raw.githubusercontent.com/freelancermilonid132bd-ui/apphub/refs/heads/main/india.m3u",
                ),
            ],
        ),
        MediaProviderResponse(
            id="free_iptv_2",
            name="Free TV",
            logo_url="https://example.com/images/free_logo.png",
            is_active=True,
            categories=[
                MediaCategoryResponse(
                    id="SportzfySpecial",
                    title="Sportzfy Special",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/sportzyf-1.webp",
                    color_hex="#FF9800",
                    playlist_url="https://raw.githubusercontent.com/streamifytv/abbas/refs/heads/main/bd.m3u",
                ),
                MediaCategoryResponse(
                    id="JagoBD",
                    title="JagoBD",
                    type="live",
                    logo_url="https://www.jagobd.com/wp-content/uploads/2015/10/web_hi_res_512.png",
                    color_hex="#FF9800",
                    playlist_url="https://m3u-tvb.pages.dev/Jjago.br.m3u8",
                ),
                MediaCategoryResponse(
                    id="Pakistan",
                    title="Pakistan",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/pak.webp",
                    color_hex="#FF9800",
                    playlist_url="https://playlists-by-playztv.pages.dev/c-pkk.m3u",
                ),
                MediaCategoryResponse(
                    id="DAZN",
                    title="DAZN",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/dazn-1.webp",
                    color_hex="#FF9800",
                    playlist_url="https://wasitv-pro.site/sportz.php?token=1wzIrANIxEtHDHKdVw9yYSddXRs_wyxn3PzVQN_mnIF4",
                ),

                MediaCategoryResponse(
                    id="CanaisdoBrasil",
                    title="Canais do Brasill",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/brasil.webp",
                    color_hex="#FF9800",
                    playlist_url="https://wasitv-pro.site/sportz.php?token=1wzIrANIxEtHDHKdVw9yYSddXRs_wyxn3PzVQN_mnIF4&gid=348832819",
                ),
                MediaCategoryResponse(
                    id="SunNXT",
                    title="Sun NXT",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/sun.webp",
                    color_hex="#FF9800",
                    playlist_url="https://playlists-by-playztv.pages.dev/snxt",
                ),

                MediaCategoryResponse(
                    id="AfricanSports",
                    title="African Sports",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/clipboard-image-1774685432.png",
                    color_hex="#FF9800",
                    playlist_url="https://wasitv-pro.site/sportz.php?token=1wzIrANIxEtHDHKdVw9yYSddXRs_wyxn3PzVQN_mnIF4&gid=369105542",
                ),
                MediaCategoryResponse(
                    id="ArabicSports",
                    title="Arabic Sports",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/arab-1.webp",
                    color_hex="#FF9800",
                    playlist_url="https://wasitv-pro.site/sportz.php?token=1wzIrANIxEtHDHKdVw9yYSddXRs_wyxn3PzVQN_mnIF4&gid=1185593386",
                ),
                MediaCategoryResponse(
                    id="Fancode-IND",
                    title="Fancode - IND",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF9800",
                    playlist_url="https://raw.githubusercontent.com/doctor-8trange/zyphx8/refs/heads/main/data/fancode.m3u",
                ),
                MediaCategoryResponse(
                    id="Fancode-BD",
                    title="Fancode - BD",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF9800",
                    playlist_url="https://raw.githubusercontent.com/doctor-8trange/zyphx8/refs/heads/main/data/bd.m3u",
                ),  
                MediaCategoryResponse(
                    id="YuppTV",
                    title="Yupp TV",
                    type="live",
                    logo_url="https://d229kpbsb5jevy.cloudfront.net/bott/v2/networks/circularimages/yupptv.png",
                    color_hex="#FF9800",
                    playlist_url="https://raw.githubusercontent.com/streamifytv/abbas/refs/heads/main/Yupp.m3u",
                ),
            ],
        ),
        MediaProviderResponse(
            id="fancode_provider",
            name="Fancode",
            logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
            is_active=True,
            categories=[
                MediaCategoryResponse(
                    id="streamifytv_tamasha",
                    title="Tamasha",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/streamifytv/abbas/refs/heads/main/tamasha.m3u8",
                ),
                MediaCategoryResponse(
                    id="streamifytv_onlynews",
                    title="Only News",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/streamifytv/abbas/refs/heads/main/onlynews.m3u",
                ),
                MediaCategoryResponse(
                    id="streamifytv_music",
                    title="Music",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/streamifytv/abbas/refs/heads/main/music.m3u",
                ),
                MediaCategoryResponse(
                    id="streamifytv_jijagobr",
                    title="Jijago BR",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/streamifytv/abbas/refs/heads/main/jijagobr.m3u",
                ),
                MediaCategoryResponse(
                    id="streamifytv_combined_playlist",
                    title="Combined Playlist",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/streamifytv/abbas/refs/heads/main/combined_playlist.m3u",
                ),
                MediaCategoryResponse(
                    id="streamifytv_bd",
                    title="BD Streamify",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/streamifytv/abbas/refs/heads/main/bd.m3u",
                ),
                MediaCategoryResponse(
                    id="abusaeeidx_bdxtv",
                    title="BDxTV",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/abusaeeidx/BDxTV/refs/heads/main/playlist_s.m3u",
                ),
                MediaCategoryResponse(
                    id="abusaeeidx_crichd_all",
                    title="CricHd ALL",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/abusaeeidx/CricHd-playlists-Auto-Update-permanent/refs/heads/main/ALL.m3u",
                ),
                MediaCategoryResponse(
                    id="abusaeeidx_iptv_scraper",
                    title="IPTV Scraper Zilla",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/abusaeeidx/IPTV-Scraper-Zilla/main/combined-playlist.m3u",
                ),
                MediaCategoryResponse(
                    id="abusaeeidx_mrgify_bdix",
                    title="Mrgify BDIX",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/abusaeeidx/Mrgify-BDIX-IPTV/refs/heads/main/playlist.m3u",
                ),
                MediaCategoryResponse(
                    id="abusaeeidx_mrgify_channels_json",
                    title="Mrgify BDIX JSON",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/abusaeeidx/Mrgify-BDIX-IPTV/refs/heads/main/Channels_data.json",
                ),
                MediaCategoryResponse(
                    id="abusaeeidx_yupptv",
                    title="YuppTV",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/abusaeeidx/Yupptv-Playlist/refs/heads/main/playlist.m3u",
                ),
                MediaCategoryResponse(
                    id="abusaeeidx_yupptv_v2",
                    title="YuppTV v2",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/abusaeeidx/Yupptv-Playlist/refs/heads/main/playlist_v2.m3u",
                ),
                MediaCategoryResponse(
                    id="abusaeeidx_tsports",
                    title="T-Sports",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/abusaeeidx/T-Sports-Playlist-Auto-Update/refs/heads/main/combine_playlist.m3u",
                ),
                MediaCategoryResponse(
                    id="abusaeeidx_crestsport_bd",
                    title="CrestSport BD",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/abusaeeidx/CrestSport-IPTV-Collection/refs/heads/main/bd.m3u",
                ),
                MediaCategoryResponse(
                    id="abusaeeidx_crestsport_default",
                    title="CrestSport Default",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/abusaeeidx/CrestSport-IPTV-Collection/refs/heads/main/default.m3u",
                ),
                MediaCategoryResponse(
                    id="abusaeeidx_ip_stream",
                    title="IP Stream",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/abusaeeidx/IP-Stream/refs/heads/main/playlist.m3u",
                ),
                MediaCategoryResponse(
                    id="abusaeeidx_toffee",
                    title="Toffee",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/abusaeeidx/Toffee-playlist/refs/heads/main/ott_navigator.m3u",
                ),
                MediaCategoryResponse(
                    id="konanda_sg_asia",
                    title="Asia",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/konanda-sg/Exp/refs/heads/main/Asia.m3u",
                ),
                MediaCategoryResponse(
                    id="konanda_sg_sports",
                    title="Sports",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/konanda-sg/Exp/refs/heads/main/Sports.m3u",
                ),
                MediaCategoryResponse(
                    id="konanda_sg_ebr",
                    title="Ebr",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/konanda-sg/Exp/refs/heads/main/Ebr",
                ),
                MediaCategoryResponse(
                    id="konanda_sg_muji",
                    title="Muji",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/konanda-sg/Exp/refs/heads/main/Muji",
                ),
                MediaCategoryResponse(
                    id="konanda_sg_sports777",
                    title="Sports777",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/konanda-sg/Exp/refs/heads/main/Sports777",
                ),
                MediaCategoryResponse(
                    id="konanda_sg_sm_live_tv",
                    title="SM Live TV",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/konanda-sg/SM-Live-TV/refs/heads/main/Combined_Live_TV.m3u",
                ),
                MediaCategoryResponse(
                    id="konanda_sg_stream99",
                    title="Stream99",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/konanda-sg/stream99/refs/heads/main/live_tv_channels.m3u",
                ),
                MediaCategoryResponse(
                    id="konanda_sg_bigboy",
                    title="BiGBoY",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/konanda-sg/MPD/refs/heads/main/BiGBoY",
                ),
                MediaCategoryResponse(
                    id="konanda_sg_favourites",
                    title="Favourites",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/konanda-sg/MPD/refs/heads/main/Favourites",
                ),
                MediaCategoryResponse(
                    id="konanda_sg_jt",
                    title="JT",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/konanda-sg/MPD/refs/heads/main/JT",
                ),
                MediaCategoryResponse(
                    id="konanda_sg_mpd",
                    title="MPD",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/konanda-sg/MPD/refs/heads/main/MPD",
                ),
                MediaCategoryResponse(
                    id="konanda_sg_samsung",
                    title="Samsung",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/konanda-sg/MPD/refs/heads/main/Samsung",
                ),
                MediaCategoryResponse(
                    id="srhady_tapmad_bd",
                    title="Tapmad BD",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/srhady/tapmad-bd/refs/heads/main/tapmad_bd.m3u",
                ),
                MediaCategoryResponse(
                    id="srhady_tapmad_bd_json",
                    title="Tapmad BD JSON",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/srhady/tapmad-bd/refs/heads/main/tapmad_bd.json",
                ),
                MediaCategoryResponse(
                    id="srhady_live_sports_json",
                    title="Live Sports JSON",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/srhady/data/refs/heads/main/live_sports_playlist.json",
                ),
                MediaCategoryResponse(
                    id="srhady_data_playlist_json",
                    title="Data Playlist JSON",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/srhady/data/refs/heads/main/playlist.json",
                ),
                MediaCategoryResponse(
                    id="srhady_bingstream",
                    title="Bingstream",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/srhady/bingstream/refs/heads/main/playlist.m3u",
                ),
                MediaCategoryResponse(
                    id="srhady_bingstream_json",
                    title="Bingstream JSON",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/srhady/bingstream/refs/heads/main/playlist.json",
                ),
                MediaCategoryResponse(
                    id="srhady_axsports",
                    title="AX Sports",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/srhady/axsports/refs/heads/main/playlist.m3u",
                ),
                MediaCategoryResponse(
                    id="srhady_axsports_json",
                    title="AX Sports JSON",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/srhady/axsports/refs/heads/main/live_sports.json",
                ),
                MediaCategoryResponse(
                    id="srhady_sonyliv",
                    title="SonyLiv",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/srhady/SonyLiv/refs/heads/main/sonyliv_playlist.m3u",
                ),
                MediaCategoryResponse(
                    id="srhady_sonyliv_json",
                    title="SonyLiv JSON",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/srhady/SonyLiv/refs/heads/main/sonyliv_playlist.json",
                ),
                MediaCategoryResponse(
                    id="srhady_streamcentre_json",
                    title="Stream Centre JSON",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/srhady/streamcentre/refs/heads/main/strmcntr_cache.json",
                ),
                MediaCategoryResponse(
                    id="srhady_crichd_special",
                    title="CricHD Special Live",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/srhady/crichd-speical-live-event/refs/heads/main/playlist.m3u",
                ),
                MediaCategoryResponse(
                    id="srhady_cricket_live",
                    title="Cricket Live",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/srhady/CricketLive/refs/heads/main/playlist.m3u",
                ),
                MediaCategoryResponse(
                    id="srhady_toffee_1",
                    title="Toffee 1",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/srhady/toffee-bd/refs/heads/main/toffee_playlist.m3u",
                ),
                MediaCategoryResponse(
                    id="srhady_hady_own",
                    title="Hady Own",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/srhady/Hady/refs/heads/main/Own.m3u",
                ),
                MediaCategoryResponse(
                    id="srhady_akash_live",
                    title="Akash Live",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/srhady/Hady/refs/heads/main/akash_live.m3u",
                ),
                MediaCategoryResponse(
                    id="srhady_aynaott",
                    title="AynaOTT",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/srhady/AynaOTT/refs/heads/main/aynaott.m3u",
                ),
                MediaCategoryResponse(
                    id="srhady_aynaott_json",
                    title="AynaOTT JSON",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/srhady/AynaOTT/refs/heads/main/aynaott.json",
                ),
                MediaCategoryResponse(
                    id="johirxofficial_otv",
                    title="OTV",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/johirxofficial/otv-auto-updated-playlist/refs/heads/main/otv.m3u",
                ),
                MediaCategoryResponse(
                    id="johirxofficial_aynaott_auto",
                    title="AynaOTT Auto Update",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/johirxofficial/aynaott-auto-update-playlist/refs/heads/main/AynaOTT.m3u",
                ),
                MediaCategoryResponse(
                    id="johirxofficial_aynaott_json",
                    title="AynaOTT Auto Update JSON",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/johirxofficial/aynaott-auto-update-playlist/refs/heads/main/AynaOTT.json",
                ),
                MediaCategoryResponse(
                    id="johirxofficial_toffee_2",
                    title="Toffee 2",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/johirxofficial/Toffee-Auto-Playlist/refs/heads/main/toffee_playlist.m3u",
                ),
                MediaCategoryResponse(
                    id="johirxofficial_toffee_json",
                    title="Toffee 2 JSON",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/johirxofficial/Toffee-Auto-Playlist/refs/heads/main/toffee_playlist.json",
                ),
                MediaCategoryResponse(
                    id="binod_xd_toffee_json",
                    title="Toffee 3 JSON",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/BINOD-XD/Toffee-Auto-Update-Playlist/main/toffee_channel_data.json",
                ),
                MediaCategoryResponse(
                    id="johirxofficial_otv_bd_may",
                    title="OTV BD May",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/johirxofficial/johirxofficial.github.io/refs/heads/main/live/otv_bd_may.m3u",
                ),
                MediaCategoryResponse(
                    id="time2shine_combined",
                    title="Time2Shine Combined",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/time2shine/IPTV/refs/heads/master/combined.m3u",
                ),
                MediaCategoryResponse(
                    id="ashik4u_iptv_bot_all",
                    title="IPTV Bot All",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/ashik4u/iptv-m3u-bot/refs/heads/main/output/all.m3u",
                ),
                MediaCategoryResponse(
                    id="ashik4u_mrgify_clean",
                    title="Mrgify Clean",
                    type="live",
                    logo_url="https://apkfolder.io/wp-content/uploads/2026/03/fc.webp",
                    color_hex="#FF5722",
                    playlist_url="https://raw.githubusercontent.com/ashik4u/mrgify-clean/refs/heads/main/playlist.m3u",
                ),
            ],
        ),
        MediaProviderResponse(
            id="adult_18",
            name="Adult",
            logo_url="https://example.com/images/free_logo.png",
            is_active=True,
            categories=[
                MediaCategoryResponse(
                    id="adult_18",
                    title="Adult (18+)",
                    type="vod",
                    logo_url="https://raw.githubusercontent.com/freelancermilonid132bd-ui/apphub/refs/heads/main/18-plus-age-restriction-icon.svg",
                    color_hex="#F44336",
                    playlist_url="https://raw.githubusercontent.com/freelancermilonid132bd-ui/apphub/refs/heads/main/adult.m3u",
                    requires_pin=False,
                ),
            ],
        )
    ]
)

@router.get("/media/providers", response_model=MediaConfigResponse, tags=["Media Center"])
async def get_media_providers() -> MediaConfigResponse:
    """
    Get the configuration for the Media Page, including active IPTV providers and their categories.
    """
    return MediaConfigResponse(
        status="success",
        data=DUMMY_MEDIA_CONFIG
    )


